
  Metrics/LineLength:
    Max: 500
  Metrics/MethodLength:
    Max: 500
  Metrics/AbcSize:
    Max: 500



  Metrics/BlockLength:
  #  ExcludedMethods: [‘describe’, ‘context’]
   Exclude:
     - ‘Rakefile’
     - ‘**/*.rake’
     - ‘test/**/*.rb’
     - 'config/environments/production.rb'
     - 'spec/controllers/posts_controller_spec.rb'
     - 'app/models/application_record.rb'
     - 'db/schema.rb'
     - 'spec/features/user_signs_up_spec.rb'
     - 'app/controllers/posts_controller.rb'
     - 'spec/features/user_can_submit_posts_spec.rb'

  Style/Documentation:
    Include:
     - app/models/**/*
     - lib/**/*

  Documentation:
    Enabled: false

  AllCops:
    Exclude:
      - 'bin/setup'
      - 'bin/update'

