Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Include:
    - 'app/views/*'
    - 'app/controllers/*'
    - 'app/models/*'
    - 'spec/*'
  Exclude:
    - 'bin/*'
    - 'db/*'
    - 'log/*'
    - 'public/*'
    - 'lib/*'
    - 'config/*'
    - 'spec/spec_helper.rb'

