require: rubocop-rails

AllCops:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/posts_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'bin/setup'
    - 'bin/update'
    - 'config/application.rb'
    - 'db/migrate/20170526114520_create_posts.rb'
    # one below is failing due to size of line
    # but line size
    # is needed for rspec test to function will look into
    - 'spec/features/show_post_time_spec.rb'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
