# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
require: rubocop-rspec

RSpec/DescribeClass:
  Exclude: 
    - 'spec/features/*'

RSpec/Be:
  Enabled: false

RSpec/ExampleLength:
  Max: 12
  
RSpec/EmptyExampleGroup:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Metrics/LineLength:
  Max: 100

RSpec/MultipleExpectations:
  Max: 2

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
