language: ruby

rvm:
  - 2.5.0

install:
  - bundle install

env:
  - RAILS_ENV=test

script:
  - bundle exec rake spec


# services:
#   - postgresql
#
# before_script:
#   - psql -c 'create database pgapp_test;' -U postgres
