language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
  - export TZ=Europe/London
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
deploy:
  provider: heroku
  app: octobook-team
  api_key: $HEROKU_API
  run: "rake db:migrate"