
language: ruby
rvm:
  - 2.5.0
services:
  - postgresql
script:
  - bundle install
  - bin/rails db:create
  - bin/rails db:migrate
  - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: bMeDjduYNSFligajp27RZlsnlZhvIJUV7rocAIsRgu0PkGYheDSJjXS1/4b6DpvRpWomC4ilMZVJ1VkFx3NKo6EkOq1B4JVsYTKe6K68QldQzf5fJcfv8IaHCB242DbaF1lH7vEON3E8O4EnPgy6uTirajXr0KWCyh2yRGKp7xEt1B7J6Xvq95n4mzTDbzOCBG+cJHKkofBSCa8MBDNv8AYhFup0TZFFX5VIZ3VhJy3oCjjBAlGYN4CBtTx8E89kMIV0A4oo9JWkY9GFi82nqp2yZg94hKuyMVg398iMJxRWo8LzC5z56vXAQkaiQgeDGG1Es2dobUrf6QQW5WOZC0SSVMNc1LnHWqXJZ8u7Hq9iYlqltTa83yNW9MI9Qugz7P93PRti0seqzy2lXhcmk9CHtA/wXy6TrWEsSeaIQBj7fknon6KwmIxG6SGWRhs9PQT01S3qxcKMNpGxThkAasyKxtRJVjMYL9CoVz0fKZnKooKWwJ1UPv9V+r/81UTL0Jt6C0zVnHKxSFDrk/hv16XF3tS1Cb8ftZLnI85idPNj6eIbX3B35l3BpJyxHDjyvR1R8vR8fV3cS+sznIXebBg6kS7rxbwYCap58I3kv2JEezupSMssNS5v5cKAji7cnvXhNw/iWqj5chtKuQpZLZH+bGTYCn0y0F/O60F7ROc=
  app: good-guys
  on:
    repo: GuyCalloway/acebook-good-guys
run:
- 'rake db:migrate'
- restart