language: ruby
rvm:
 - 2.5.0

script:
 - gem install bundler
 - bundle install
 - bundle exec rake db:create
 - bundle exec rake db:migrate
 - bundle exec rspec --format doc

deploy:
  provider: heroku
  api_key:
    secure: "fw7kozI4EPBv/2JY902ANHNvmmZAfZLYnyc7HUh83ygWAtPeqWRNZqgPVc61fGZj5L8oQhCsyWNwpxkLqEPKp7TrG0Xs2I4UxM2W7f/aRKE/6fmFWLoYiE8i+W1tvwxXgt
Q1mbU5aNx+ZsSeQmlFUVxSssA0rPv80fT/HmpQWRDq4jr+DzWpfUKJWNfUZXXwtc48NuaRPmxqnsdb8PS0TCFQDEGqUacqEg3Mc83PtQAwIdc31g63OoJvdhpgrELD2cuRbFL6jgHoAUD
XuYZFoydOE2yGJ1hObrwQXVY6wBXOxgqjhovhIdES2WGKdU0FNrTo0aKmYzi5nfD4azv+cm10e/z40FXY6QAOOwI8Va0CI/zeho5wvWg2Urqdu5FHZbleWJ3tdaAkABCeptGt1WkhQ3uc
sgAGB6LU3+ZJYqNJeCg/OUQS+hn6lTNZ4pcAcMnSgosvKC3y+N6EOfDyaZNTtiKq2vZBeV/Z+u4e4MPEDcWBCrZONEDrgWN7bG7wyiz11OxFKQL+ZDluc8PoBC6AFBoh8TugsvG8xgW85w1Vp0+Sq/FH2twzP1QDkW3FuTmvY12HgiYEEi6CwdmMQAGnFZAmedgav/CMDADVwqZ6k8vBYIykmx/aKknteub7tJfKAU2UH/QhmvRm5oRHTrml325yS39rbei1ie4mmao="
