language: ruby

rvm:
  - 2.5.0

services:
  - postgresql

before_script:
  - psql -c 'create database pgapp_test;' -U postgres
  - bundle exec rake db:migrate

# telling travis to run psql command:
# connect to database with the specified name
# connect to postgres database
# run migrations so database schema is created

# maybe we also need to add this into the database.yml:
# test:
#   adapter: postgresql
#   database: travis_ci_test

# and then add the following into this file:
# before_script:
#   - cp config/database.yml.travis config/database.yml
