language: ruby
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
# addons:
#   code_climate:
#     repo_token:
#       secure: "csjYAIA5RYfzE2RbS5sfzZkxDpYIA2h/EgW5VRjVqLVG+WQTbVibGrX8bRWFxrQ+7PxlMIImGb/OT8+fZkYW/wLRkfEmPJ4j0xjOnvMxGO7/v7seqavvUj3KsqTwk7yfdzLl9Ot72+WE9COBfWefF+N6an27RejQkIk1e5BY6z3Ue1PM6KFDzZGYMGtaUzrpEIGv7Mc2PZJG8DvyBbruabaLXoSDfUZuVMxjvtSZRc2TivSlMTK6nFEYqIGW5Pjq9d1gdwVJ/aTyapzhVwUWgri++jR+2ms5J5Axx3PEhoqG6QpMn2mfPoh6EnaYtMU/G6oQRSSYcv0vAmAKMIX5diKWfdrQuzCZII2CQUElL+GJx+IrRa1LuYYqoQNQsEKo1yCHdqdYGBcFM6Imuqj6QiaU4JumafqbkZ7B5HNtRZOV4tgFWjmQwp1wbwpkHZ7jGH1btElogF6vGubeKP2+JX2x6Ejs/EwsJV6Ly6OC43A4sT/zu5Y/CEQrNEVnKieSgefd4fg2PAk+W8ONqrBJ48lpEv2VMUt1IHJmpVPPSkL6vlDcX5Hji0nzA/tMtAXojS8Tk5tCDMvpU9gnnTm64rVDg/yjzaWhpPEqVr+RzW8xKlsJHm0MNEKg7SWtoD02qzYZIP9i6/Vo79qsa1E9mQFnV+5d/yN23Yyqbzn2dio="
env:
  global:
    CC_TEST_REPORTER_ID=6dc1522b4344fa94cb327359009aa386080f3a38d88056b146b340e62a19ddd1
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - bundle exec rake db:test:prepare
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
  - bundle exec rubocop
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT # Upload coverage/codeclimate.json
deploy:
  provider: heroku
  api_key:
    secure: DK23+3rPctVmdBY92LIwYqsStvXBr2DMv8VtkgkJSIyyPJ9Oh4KTgMPdFUE7EUdBP0AGJKGTeeny36jA3SwUQqpqYSViG6grrVIf5iW0Rh2SIl5AUz9pfWqRnUzuZCEj8EKfroVcLEGXRFEBtGmYnA48g3Uv19XX+7TsfFzJTJPhlrcinwgUlFVKQj3gKwY/9Wn4A4FgBQqMVfih3PG7LzYJnIdUDxTJwOYNRGfajduhJz4GCeOnqtU8LcgX4TpWoxFZUdb5D7o9ElzGPMlEb8AKbBA/OPf9ncLEMppSttc0RZgCaL2ncx0OQkReEtRTmxVIuootqgdEZeuf6/o1ljF7FUqk/Ef3pO5Higc54cv7uJfYEraPNFz8HNMyXcyvJKvCkgoD9h1fEIrQNSkkPLbQbC8UqQVX/dRrV90qXsvOIJWPU8lwFiB04+6QgLA1s3EjG+iLT+W+4xkLppODv3T4vtP+J4MEDoIIJ/A0lVNB52FINjSsXA54/75/gEMn6493UuOdMFx2iuhOfA3ftm9LgOKjmdXM+nZcr8ksi5IRDEhMuNNK6NnEadV+sFPZ02wBckkuhfSwd1Yt5q7AjbIVMl/PBg+IDu2ZGUH/9DtWqwTkCcrvMFuX7ZMGB4VGl/C1OWRFqkCtq16dmhQZYOyxtftWs99YsWLWjQKUFOI=
  app: acebookderailed
  on:
    repo: basselalsayed/acebook-derailed
