language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '2.1.4'
  - bundle install
rvm:
  - 2.7.1
services:
- postgresql
before_script:
- bin/rails db:create
- bin/rails db:migrate
script:
- bundle exec rspec
after_success:
- bundle config set deployment 'true'
