language: ruby

rvm:
- 2.5.0
  # can specify many versions of ruby if you like
os: osx

install:
# - gem uninstall bundler
# - gem install bundler --version '1.7.4'
- bundle install
- rails db:create
- rails db:migrate

# deploy:
#   skip_cleanup: true



services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE user_test;'
   - psql -U postgres -c 'CREATE DATABASE post_test;'

script:
    - bundle exec rake
    - bundle exec rspec 
