language: ruby
rvm:
- 2.5.0
dist: trusty
services:
- postgresql
script:
- bundle install
- bundle exec bin/rails db:create
- bundle exec bin/rails db:migrate
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: UTWiDJDYQo+1bE9tSRuYnL2swsLb4MgMaEKix+Lj9VwdbDTZVjMOWDHyf3/b6rX/yuB/XpPoFjWk8MEqevzSbXzsYlSoRQ5GD3V4mB/Pa0bsZXZKcGGliOm6f0VugtqBG3C5EQj64iVxIhUq/J5gA8ff3E6HceQIO89fq1sXSa88NzkAEVr9KRqaUXPiI+0nWNxLasx+aLV9rMPrrfUj9Lk9+/nnblpo1cqXvXLNGlISr/pMb4oB8R/2b7F57SQlAB6a1MGHgygV17yRcFI4Iy3GPbX8+BSdDyXLKVWQNtYEDdttMD5AavbC5Nn+MbI7VyRsdvhoiKQtZJMxmT2sVHrxLJhovRD4yYtYO5MKyph5lx/7ARK/Rg9b+DnQVjIAAerKM5ojH8SseEqMFb2eKeM9UugtaLQTcSizSV93o+pAFveBSVdGOOcGL4LaffmKN9ugXgAB8XUZ35K1yQ5lYhubWOBpfct8DkLbPl/8dY8MHFS6dzotAi6vDx/Trb96LCXiFex2Yov+RgtobIXcNSJPZtyjH1Pg3F7J1sXXSFastVO48W4dBS0PzogFp4KdMMbShlFq6mH2XEesv3mwoUF9JenNJp4vEhtPdM6MZLptZnGxVNhK/RsdAu1woonPcqzLAwTQlAKHqAd23n8UclOetcy6+ECCS/TjLrWA9vo=
  app:
    master: acebook-akers-cademy
  on:
    repo: sujee09/acebook-akers-cademy
