language: ruby
rvm:
- '2.5.0'
# - jruby-19mode
# - rbx-2

env:
  - DB=postgresql

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake

before_script:
  - cp config/database.yml.travis config/database.yml
  # - mysql -e 'create database mydb_test'
