addons:
  postgresql: 9.5

before_script:
  - psql -c 'create database pgapp_test;' -U postgres

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec

language: ruby

rvm:
  - 2.5.0
