language: ruby
rvm:
- 2.5.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- bundle install --jobs=3 --retry=3
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  - false

env:
  global:
    - CC_TEST_REPORTER_ID=d9fe39387a1482e4a4d83a6aa41f6991c9967e13c5ed45bb679f9e8b01eb67db

deploy:
  - provider: elasticbeanstalk
    access_key_id: AKIAI332QGQMWO67EKUA
    secret_access_key:
      secure: ku8jhHvHWG+9YIXo5fo+lK1fnJLRZdlBUmGiGIiPVaHvnytZUWxdtBdSsyIO1bpgD749rjIa6RtltgtRlX0H4+ECLlIX4pSFU2nvpsV0EytxK593Oq3CAXW9NMytW4OS9jLLC6Km+R5qUX5IITkPvmw/6WuEnrMD59qvEqK0fxy7yi2RVPyCNwSWJmxjLRGaCFmKPyCWN6cdiS6Y023oXaM41dM4hvfEjo9Ht/GUNWb2BPgf0l8T3+H9EpRAEwv2jFKsy53OGr7UvF0yqOvC56NzKta+Om/MLr17ONQrrWd0d5Vfweg/iEx3s4aexK3NfaMBx5qsWqPe4gXAn591AXS2GLwDEZlpEzSoMRGq7b95lEj+AHV6/UBAv9moJhSp01s7C6b3k/icuI9pk8HLPSXUoeV3hSLm8kdIQfO+t4MHWIGbqVVDJeN9gx1bPyZDGvwlZtvme6rjYf6VTOZQBJsE89hinvnrWbB9nAewgfWhrqjYdIoIf8UUrUO/q/k5KUZ37kIdAFM4S9//q+HqGqVay18CJaA989L0dNM4kXab0iwJ/vpwwnG7stnTQ0jVPiWBcnVMzfp9+OYj1ud8aIFRNJwyGgRN6NLPunSSzs14lzYEuqVQLfxj7dhAy60AH8unQGJsS7IPkGtLL+ix/bP9nNTBxiY+xYmbeOLVWQU=
    region: eu-west-2
    app: acebook-FullStaxx
    env: acebook-fullstaxx-env
    on:
      branch: master
      repo: VivianAllen/acebook-FullStaxx
    bucket_name: "elasticbeanstalk-eu-west-2-862365935758"
  - provider: elasticbeanstalk
    access_key_id: AKIAI332QGQMWO67EKUA
    secret_access_key:
      secure: ku8jhHvHWG+9YIXo5fo+lK1fnJLRZdlBUmGiGIiPVaHvnytZUWxdtBdSsyIO1bpgD749rjIa6RtltgtRlX0H4+ECLlIX4pSFU2nvpsV0EytxK593Oq3CAXW9NMytW4OS9jLLC6Km+R5qUX5IITkPvmw/6WuEnrMD59qvEqK0fxy7yi2RVPyCNwSWJmxjLRGaCFmKPyCWN6cdiS6Y023oXaM41dM4hvfEjo9Ht/GUNWb2BPgf0l8T3+H9EpRAEwv2jFKsy53OGr7UvF0yqOvC56NzKta+Om/MLr17ONQrrWd0d5Vfweg/iEx3s4aexK3NfaMBx5qsWqPe4gXAn591AXS2GLwDEZlpEzSoMRGq7b95lEj+AHV6/UBAv9moJhSp01s7C6b3k/icuI9pk8HLPSXUoeV3hSLm8kdIQfO+t4MHWIGbqVVDJeN9gx1bPyZDGvwlZtvme6rjYf6VTOZQBJsE89hinvnrWbB9nAewgfWhrqjYdIoIf8UUrUO/q/k5KUZ37kIdAFM4S9//q+HqGqVay18CJaA989L0dNM4kXab0iwJ/vpwwnG7stnTQ0jVPiWBcnVMzfp9+OYj1ud8aIFRNJwyGgRN6NLPunSSzs14lzYEuqVQLfxj7dhAy60AH8unQGJsS7IPkGtLL+ix/bP9nNTBxiY+xYmbeOLVWQU=
    region: eu-west-2
    app: acebook-FullStaxx
    env: AcebookFullstaxx-staging-env2
    on:
      branch: staging
      repo: VivianAllen/acebook-FullStaxx
    bucket_name: "elasticbeanstalk-eu-west-2-862365935758"
