language: ruby
services:
  - postgresql
before_script:
  - psql -c 'create database pg_app_test;' -U postgres
script:
 — bundle install — jobs=3 — retry=3 - without deployment
 — bundle exec rake db:schema:load RAILS_ENV=test
 — bundle exec rake db:migrate
 — bundle exec rspec
