# addons:
#   postgresql: 10.3
before_script:
- bin/rails db:create
# - bin/rails db:migrate

  #- cp config/database.yml.travis config/database.yml
 # - psql -c 'create database pgapp_test;' -U postgres
  #- gem install bundler
dist: trusty
language: ruby
rvm:
  - 2.5.0
script:
  - bundle exec rspec
  - bundle exec rails db:migrate RAILS_ENV=test
services:
  - postgresql: "10.3"
