before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
cache: bundler
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: zXP8lYdOzHmMeaIbYjYlT6hbCxv8S+x1UMVGHPnVGTpMNoS0xCWM7vlVE8shjUph81d3lDMgCvS8r6cW8vx7EDwS5uaH5T1lDKku2vWrAIVLG7pk5dU8R4ZE4pTPU6rq8pkB8uoi1Fiwi+tr7ulw1RBmOFySGsIx9chvGtI6jMSJDwfN/rKqyN+DUS9q0AWTev0n2Ag6UhMXyeYTvWc1B9NwGGyNJu6Rr0rx+mJPElj2hqVw9IWY6MEVD2SF3DX4ZmcUmmqlsZbxFzMV6tQ5zqUtzl+uLxFCdZhARbRg14NdGEA2iDm0fNiUBDIvjVMQhsfMe4z77pms1XQ5XmEboNHaSSTb7TJRAMUKlLOzrX8TcUROjQwmH9Zh/glyyZ1l9Uu2IJrSsSpt3ltPXHtjsb9W1a+GRwgLin0HeLCiiVWV9qiyzpNUpm7HVs7br8OlEfQL2IbrDQdYx/TmGR2m0PIgQj80kHG7uMSH3RIaSC0qZgqtwZLATZv0A4pnkjayqU15k2wpEvKU9JBDli5mNL/7VLwH268DjjKtirsGfoSzpqYGNG/0nxoV3OsSyxQGSlHeYwdEpBXrUO4RZLOtnxluxJXqRvpaR1uI4GTmp25CS+v/HVIcP8NQ0bsDcWbQh8/fS4PNH9+0OXmLH4IjLZGlFe34kERcGtwEHNA04Y8=
  app: aqueous-wave-77193
  run: rake db:migrate
  on:
    repo: tomasdoh/acebook-floppy-disk
    branch: master
  skip_cleanup: true
