language: ruby
rvm: 2.5.0
sudo: required
dist: trusty
services:
  - postgresql
before_install:
  - yes | gem update --system --force
  - gem install bundler -v '2.1.2'
cache: bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - export TZ=Europe/London
