language: ruby
rvm:
  - 2.5.0
cache: bundler
services: postgresql
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rubocop
  - bundle exec rspec spec
