lanugage: ruby 

rvm: '2.5.0'

addons:
  postgresql: 9.6

env:
  - DB=pgsql


before_script:
  - bundle exec rake db:create

script:
  - bundle exec rake db:migrate RAILS_ENV=test 
  - bundle exec rspec


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-west-2"  
  app: "acebook-zukerbros2"
  env: "production"
  bucket_name: "elasticbeanstalk-eu-west-2-290974039617"
  on:
    branch: master

after_deploy: "echo 'deployed'"