language: ruby
rvm:
  - 2.5.0
dist: trusty
services:
  - postgresql
script:
  - bundle install
  - bundle exec bin/rails db:create
  - bundle exec bin/rails db:migrate
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: pbTHRrs8iZT27hBzys1fjED+Si/DCW6DebVcoHOHondOA0E2ZFbaoqreDA8JnxYKm4pK8/kgjyFIsmBsP2aZELa9igO4jMl2e1degruesYIJBAQdUJ/Yss3DUErLy5DlSRuQHQNSTFKHQCVtDYjVFL+BTMBmoO8egW4mSEJ7GE6zDMMxgC2YDh1nq9KrDNXiwgAwRjT0TuTcJBBGeST7Lrpnv1WCnLZ+XR8/qjv3EEI+0Sz3E3XE6GyQMgjb3qsNOLwfUlhkkHXc0LrVb2hB3bz5dWp93xgjgE3j4QYpzZmiLlGg81fs6Wn85c+UN12NUCPpqBa/TKg1WWBp7nvHOe3vqUgAKadrFR/5rLxKkIeyas6pPuk2QyTCE2hIPWZXgsFJFATMPdPnuTNWLewNRWI8CEA1DTo5QTweEQ4vDrcY/HihtJekAGOy1Ypg28r+UHjTfEfVZoYzFobEVc6vcGKCCK3R9a5gszbe9gJkCFX5ijbBpJ08AoycMpT7PPHQbrsxtHiovHRe52iCQx8KwKch3OUJoR/+L4jrKLGIEY3BFqx22PG1PLZp5L1sC1e88TlxMaAyK0M6aK0yre1xzrWHM/5LeILQW8K7uo6Xv60X/bRcKTVHPpsrw5S+h0YyY1A3qDNtTrgqLHHK8YgKAqkG6F3xEeCdHp/GrqFIinQ=
  app:
    master: acebook-akers-cademy
<<<<<<< HEAD
  true:
    repo: sujee09/acebook-akers-cademy
=======
>>>>>>> fd007da7dc0cff0f51c991315517b325089d8194
