language: ruby
before_install: gem install bundler -v 1.17.3
services:
  - postgresql
before_script:
  - bin/rails db:create
  - bin/rails db:migrate
script:
  - bundle exec rspec
# deploy:
#   provider: heroku
#   api_key:
#     secure:
