language: ruby

before_script:
  - psql -c "CREATE DATABASE pgapp_test;" -U postgres

before_install:
 - gem update --system
 - gem install bundler

rvm:
 — 2.5.0

script:
 - bundle exec rspec spec

services:
  - postgresql
