language: ruby
rvm:
 - 2.5
 # - jruby

services:
- postgresql

before script:
- psql -c 'create database pgapp_test;' -U postgres

script:
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec spec
after_script:
  - bundle exec rake coveralls:push
