language: ruby

before_install:
 - gem update --system
 - gem install bundler

rvm:
 — 2.5.0

script:
 — bundle install
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec
