default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pgapp_development

test:
  <<: *default
  database: pgapp_test

production:
  <<: *default
  database: pgapp_production
  username: pgapp
  password: <%= ENV['PGAPP_DATABASE_PASSWORD'] %>
